##################################
#                                #
#     Variáveis: %chat_clear%    #
#                                #
##################################
Permissoes:
  Comandos:
    Comandos: "comandos.use"
Mensagens:
  FlyOn: " &aFly ativado com sucesso!"
  FlyOff: " &cFly desativado com sucesso!"
  ChatCleared: " &aChat limpo por: &7%chat_clear%"
  Heal: " &aFome e vida regeneradas com sucesso!"
  SemPermissao: " &cNão tens permissão para executar este comando!"
Menus:
  Comandos:
    Titulo: "&8Comandos"
    Itens:
      Fly:
        Name: "&aFly"
        Lore: "&7Clica para alterar o estado do Fly."
      FlyState:
        Name_On: "&aAtivado."
        Name_Off: "&cDesativado."
      Rain:
        Name: "&aChuva"
        Lore: "&7Clica para alterar o estado da chuva."
      Chat:
        Name: "&fChat"
        Lore: "&7Clica para limpar o chat."
      Heal:
        Name: "&2Heal"
        Lore: "&7Clica para regenerar toda a tua vida e fome."
      Filler:
        Name: "&8"