name: FUtilities
main: pt.flawless.FUtilities.Main
description: Teste description 2
version: 1.0
commands:
  tp:
  tphere:
  vida:
  invsee:
  heal:
  feed:
  clearchat:
  fly:
  gamemode:
    aliases:
      - gm
  comandos:
    aliases:
      - cmds